# Generated by Django 6.0.2 on 2026-05-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mychats',
            name='chats',
            field=models.JSONField(default=dict),
        ),
    ]
